<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>SyntheraCore</AssemblyName>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>../../Assemblies</OutputPath>
		<PlatformTarget>x64</PlatformTarget>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\..\..\..\Mods\1127530465\1.6\Assemblies\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\..\..\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
